remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: [viper - a discord bot]

description: [A Discord bot that references answers from past conversations.]

github:
  zip_url: https://github.com/viper-Deploy2023/viper